[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "nltk>=3.9.1",
    "pandas>=2.2.3",
    "pandasql>=0.7.3",
    "plotly>=6.0.1",
    "sqlalchemy>=2.0.40",
    "streamlit>=1.44.1",
]
